services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    user: "${UID:-1000}:${GID:-1000}"
    command: flask --app app run --host=0.0.0.0 --port=5000 --debug
    ports:
      - "5000:5000"
    volumes:
      - .:/app